export const PantallaAdministrarSitioLenguaje= {
    estadisticaSitios: {
      es:"Estadistica de los sitios",
      en: "Site statistics",
      ch: "网站统计",
      hindi:"साइटों की आँकड़े",
      fr:"Statistiques du sites",
      ara:"إحصائيات المواقع ",
      beng:"সাইটগুলির পরিসংখ্যান", 
      rus:"Статистика сайтов",
      port:"Estatísticas do site",
      urd:" ویب سائٹ کی شماریات", 
      de:"Website-Statistiken"
    },
    sinAprobar: {
        es: "Sin aprobar",
        en: "not approved",
        ch: " 未批准",
        hindi:"मंजूर नहीं ",
        fr:"Non approuvé",
        ara:"غير معتمد",
        beng:"অনুমোদিত নয়", 
        rus:"Не одобрено ",
        port:" Não aprovado",
        urd:"منظور نہیں", 
        de:"Nicht genehmigt"
    },
    categorias: {
      es: "Categorias",
      en: "Category",
      ch: "类别",
      hindi:"श्रेणियाँ ",
      fr:"Catégories",
      ara:"فئات",
      beng:"বিভাগসমূহ", 
      rus:"Категории",
      port:" Categorias",
      urd:"زمرے", 
      de:"Kategorien"
    },
    correo: {
      es: "correo",
      en: "Email",
      ch: "邮件",
      hindi:"मेल",
      fr:"Courrier",
      ara:"بريد",
      beng:"মেল", 
      rus:"Почта ",
      port:" Correio",
      urd:"خط", 
      de:"Post"
    },
    tituloAdministrarSitio : {
        es: 'Administrador de Sitios',
        en: 'Site Manager',
        ch: "网站管理员 ",
        hindi:"साइट प्रबंधक",
        fr:"Administrateur de site",
        ara:"مدير المواقع",
        beng:"সাইট প্রশাসক", 
        rus:"Администратор сайта",
        port:"Administrador de Site",
        urd:"سائٹ انتظامیہ", 
        de:"Website-Administrator"
    },
    noSeEncontroImagenes: {
      es: "No se encontraron imagenes",
      en: "No images found",
      ch: "没有找到图片",
      hindi:"छवियाँ नहीं मिलीं",
      fr:"Aucune image trouvée",
      ara:"لم يتم العثور على صور",
      beng:"চিত্রগুলি পাওয়া যায়নি", 
      rus:"Изображения не найдены",
      port:"Nenhuma imagem encontrada",
      urd:"تصاویر نہیں ملیں", 
      de:"Keine Bilder gefunden"
    },
    subTitulo: {
        es: 'Sitios en Revision',
        en: 'Sites in Review',
        ch: "审查中的网站",
        hindi:"समीक्षा में स्थल",
        fr:"Sites en révision",
        ara:"المواقع قيد المراجعة",
        beng:"পর্যবেক্ষণাধীন স্থান ", 
        rus:"Сайты на рецензии",
        port:"Sites em revisão",
        urd:"جائزے میں مقامات", 
        de:"Seiten in Überarbeitung"
    },
    titulo: {
        es: 'Titulo',
        en: 'Title',
        ch: " 标题 ",
        hindi:"शीर्षक ",
        fr:"Titre",
        ara:"عنوان",
        beng:" শিরোনাম", 
        rus:"Заголовок",
        port:"Título",
        urd:"عنوان", 
        de:"Titel"
    },
    departamento: {
        es: 'Departamento',
        en: 'Departament',
        ch: "部门",
        hindi:"विभाग",
        fr:"Département",
        ara:"قسم",
        beng:"বিভাগ", 
        rus:"Отдел",
        port:"Departamento",
        urd:"ڈپارٹمنٹ", 
        de:"Abteilung"
    },
    descripcion: {
        es: 'Descripcion',
        en: 'Description',
        ch: "Miáoshù",
        hindi:"Vivaraṇ",
        fr:"Description",
        ara:"Wasef",
        beng:"বর্ণনা ", 
        rus:"Описание",
        port:"Descrição",
        urd:"تفصیل", 
        de:"Beschreibung"
    },

    horario: {
        es: 'Horario',
        en: 'Schedule',
        ch: "时间表",
        hindi:"समय सारणी ",
        fr:"Horaire",
        ara:"جدول زمني",
        beng:"সময়সূচী ", 
        rus:"Расписание",
        port:"Horário",
        urd:"وقت کا تعین", 
        de:"Zeitplan"
    },
    servicio: {
        es: 'Servicios',
        en: 'Services',
        ch: "Fúwù",
        hindi:"Sēvāēṁ",
        fr:"Services",
        ara:"Khidmat",
        beng:"সেবাসমূহ", 
        rus:"Услуги",
        port:"Serviços",
        urd:"خدمات", 
        de:"Dienstleistungen"
    },
    precio: {
        es: 'Precios',
        en: 'Prices',
        ch: "Wàiguó rén",
        hindi:"Vidēśī",
        fr:"Étrangers",
        ara:"Ajanib",
        beng:"বিদেশী", 
        rus:"Иностранцы",
        port:"Estrangeiros",
        urd:"غیر ملکی", 
        de:"Ausländer"
    },
    botonAprobar: {
        es: 'Aprobar',
        en: 'Approve',
        ch: "批准 ",
        hindi:"मंजूर करना",
        fr:"Approuver",
        ara:"الموافقة",
        beng:"অনুমোদন করা", 
        rus:"Одобрить",
        port:"Aprovar",
        urd:"منظور کرنا", 
        de:"Genehmigen"
    },
    botonDenegar: {
        es: 'Denegar',
        en: 'Deny',
        ch: "拒绝",
        hindi:"अस्वीकार करना",
        fr:"Refuser",
        ara:"رفض",
        beng:"বাতিল করা", 
        rus:"Отклонить",
        port:"Negar",
        urd:" منع کرنا", 
        de:"Ablehnen"
    },
    Estudiante: {
        es: 'Estudiante',
        en: 'Student',
        ch: "Xuéshēng",
        hindi:"Chhātr",
        fr:"Étudiant",
        ara:"Talib",
        beng:"ছাত্র ", 
        rus:"Студент ",
        port:"Estudante",
        urd:"طالب علم", 
        de:"Student"
    },
    Ninos: {
        es: 'Ninos',
        en: "Child",
        ch: "Értóng",
        hindi:"Bacce",
        fr:"Enfants",
        ara:"Atfal",
        beng:"শিশু", 
        rus:"Дети",
        port:"Crianças",
        urd:"بچے", 
        de:"Kinder"
    },
    TerceraEdad: {
        es:"Tercera edad",
        en: "Third age",
        ch: "Lǎonián rén",
        hindi:"Vṛddhāvasthā",
        fr:"Troisième âge ",
        ara:"Kibar al-sin",
        beng:"তৃতীয় বয়স্ক", 
        rus:"Пожилые",
        port:"Terceira idade",
        urd:"تیسری عمر کے افرا", 
        de:"Senioren"
    },
    General: {
        es: "General",
        en: "General",
        ch: "Yībān",
        hindi:"Sāmāny",
        fr:"Général",
        ara:"Aam",
        beng:"সাধারণ ", 
        rus:"Общий",
        port:"Geral",
        urd:"عام", 
        de:"Allgemein"
    },
    Parqueo: {
        es: "Parqueo",
        en: "Parking",
        ch: "Tíngchē",
        hindi:"Pārkiṁg",
        fr:"Parking",
        ara:"Estacionamiento",
        beng:"পার্কিং", 
        rus:"Парковка",
        port:"Estacionamento",
        urd:"پارکنگ", 
        de:"Parkplatz"
    },
    Extranjeros: {
        es: "Extranjeros",
        en: "Foreign",
        ch: "Wàiguó rén",
        hindi:"Vidēśī",
        fr:"Étrangers",
        ara:"Ajanib",
        beng:"বিদেশী", 
        rus:"Иностранцы",
        port:"Estrangeiros",
        urd:"غیر ملکی", 
        de:"Ausländer"
    }


}