
// Exportamos cada const
export const PantallaInicioLenguaje = {
    tituloTexto : {
        es: 'Comienza a explorar',
        en: 'Start exploring',
        ch: "开始探索",
        hindi:"अन्वेषण शुरू करें",
        fr:"Commencez à explorer",
        ara:"ابدأ الاستكشاف",
        beng:"অন্বেষণ শুরু", 
        rus:"начать исследовать",
        port:"começar a explorar",
        urd:"دریافت کرنا شروع کریں",
        de:"Beginnen Sie mit der Erkundung",
    },
    categorias: {
        es:"Categorias",
        en:"Category",
        ch: "类别",
        hindi:"श्रेणियाँ",
        fr:"Catégories",
        ara:"فئات",
        beng:"ক্যাটাগরি", 
        rus:"Категории",
        port:"Categorias",
        urd:"اقسام",
        de:"Kategorien",
        
    },
    mensajeSinSitio: {
        es: "Parece que no hemos encontrado sitios",
        en: "It seems we haven't found any sites",
        ch: "似乎我们没有找到任何站点",
        hindi: "लगता है हमें कोई साइट नहीं मिली है",
        fr: "Il semble que nous n'ayons pas trouvé de sites",
        ara: "يبدو أننا لم نجد أي مواقع",
        beng: "এটি যে আমরা কোনও সাইট পাইনি মনে হচ্ছে",
        rus: "Похоже, мы не нашли ни одного сайта",
        port: "Parece que não encontramos nenhum site",
        urd: "لگتا ہے ہم نے کوئی ویب سائٹ نہیں پائی",
        de: "Es scheint, wir haben keine Websites gefunden",
    },
    departamentos: {
        es:"Departamentos",
        en:"Departments",
        ch: "部门",
        hindi:"विभागों",
        fr:"Départements",
        ara:"الإدارات",
        beng:"বিভাগসমূহ", 
        rus:"Департаменты",
        port:"Departamentos",
        urd:"شعبه جات",
        de:"Abteilungen",
    },
    Todos: {
        es: "Todos",
        en: "all",
        ch: "全部",
        hindi:"सभी",
        fr:"Tous",
        ara:"الجميع",
        beng:"সব",
        rus:"Все",
        port:"Todos",
        urd:"تمام",
        de:"Alle",
    },
    Colonial: {
        es: "Colonial",
        en: "Colonial",
        ch: "科隆",
        hindi:"इत्र",
        fr:"eau de Cologne",
        ara:"كولونيا",
        beng:"সুগন্ধিবিশেষ",
        rus:"одеколон",
        port:"Colônia",
        urd:"کولون",
        de:"Kolonial",
    },
    Playas: {
        es: "Playas",
        en: "Beaches",
        ch: "海滩",
        hindi:"समुद्र तटों",
        fr:"Des plages",
        ara:"الشواطئ",
        beng:"সৈকত",
        rus:"Пляжи",
        port:"Praias",
        urd:"ساحل",
        de:"Strände",
    },
    Bosques: {
        es: "Bosques",
        en: "forests",
        ch: "森林",
        hindi:"जंगलों",
        fr:"les forêts",
        ara:"الغابات",
        beng:"বন",
        rus:"леса",
        port:"florestas",
        urd:"جنگلات",
        de:"Wälder",
    },
    Museos: {
        es: "Museos",
        en: "museums",
        ch: "博物馆",
        hindi:"संग्रहालय",
        fr:"musées",
        ara:"المتاحف",
        beng:"জাদুঘর",
        rus:"музеи",
        port:"museus",
        urd:"عجائب گھر",
        de:"Museen",
    },
    Balnearios: {
        es: "Balnearios",
        en: "spas",
        ch: "水疗中心",
        hindi:"स्पा",
        fr:"les thermes",
        ara:"المنتجعات الصحية",
        beng:"স্পা",
        rus:"курорты",
        port:"spas",
        urd:"اسپاس",
        de:"Spas",
    },
    SitiosArqueologicos: {
        es: "Sitios Arqueologicos",
        en: "Archaeological sites",
        ch: "考古遗址",
        hindi:"पुरातात्विक स्थल",
        fr:"sites archéologiques",
        ara:"المواقع الأثرية",
        beng:"প্রত্নতাত্ত্বিক সাইট",
        rus:"археологические сайты",
        port:"sítios arqueológicos",
        urd:"آثار قدیمہ کے مقامات",
        de:"Archäologische Seiten",
    },
    lugaresRecomendados: {
        es: "Lugares Recomendados",
        en: "Recommended Places",
        ch: "推荐地点",
        hindi: "सुझाए गए स्थान",
        fr: "Lieux Recommandés",
        ara: "أماكن موصى بها",
        beng: "সুপারিশকৃত স্থান",
        rus: "Рекомендуемые места",
        port: "Locais Recomendados",
        urd: "مشورہ شدہ جگہیں",
        de: "Empfohlene Orte"
    },
    sitiosTuristicos: {
        es: "Sitios Turísticos",
        en: "Tourist Sites",
        ch: "旅游景点",
        hindi: "पर्यटन स्थल",
        fr: "Sites Touristiques",
        ara: "مواقع سياحية",
        beng: "পর্যটন স্থল",
        rus: "Туристические места",
        port: "Pontos Turísticos",
        urd: "سیاحتی مقامات",
        de: "Touristische Sehenswürdigkeiten"
    },
    buscandoSitios: {
        es: "Buscando los mejores sitios para ti...",
        en: "Searching for the best places for you...",
        ch: "正在寻找最适合您的地方...",
        hindi: "आपके लिए सबसे अच्छे स्थान खोज रहे हैं...",
        fr: "Recherche des meilleurs endroits pour vous...",
        ara: "البحث عن أفضل الأماكن لك...",
        beng: "আপনার জন্য সেরা স্থান খোঁজা হচ্ছে...",
        rus: "Поиск лучших мест для вас...",
        port: "Procurando os melhores lugares para você...",
        urd: "آپ کے لئے بہترین مقامات تلاش کر رہے ہیں...",
        de: "Suche nach den besten Orten für dich..."
    },
    noConexionInternet: {
        es: "No hay conexión a internet",
        en: "No internet connection",
        ch: "没有网络连接",
        hindi: "कोई इंटरनेट कनेक्शन नहीं है",
        fr: "Pas de connexion Internet",
        ara: "لا اتصال بالإنترنت",
        beng: "ইন্টারনেট সংযোগ নেই",
        rus: "Нет подключения к интернету",
        port: "Sem conexão com a internet",
        urd: "انٹرنیٹ کنکشن نہیں ہے",
        de: "Keine Internetverbindung"
    }
}
//Para acceder
//1. importamos en la pantalla el archivo que necesitamos
// PantallaInicioLenguaje['tituloTexto']['es']