export const PantallaAdministrarUsuarioLenguaje= {
    busquedaUsuario : {
        es: 'Busqueda usuario',
        en: 'User Search',
        ch: "用户搜索",
        hindi:"उपयोगकर्ता खोज ",
        fr:"Recherche d'utilisateur",
        ara:"بحث المستخدم",
        beng:"ব্যবহারকারী অনুসন্ধান ", 
        rus:"Поиск пользователя ",
        port:"Busca de usuário",
        urd:" صارف کی تلاش",
        de: ' Benutzersuche  '
    },
    buscarUsuario : {
        es: 'Buscar Usuario',
        en: 'Search User',
        ch: "查找用户",
        hindi:"उपयोगकर्ता ढूंढें",
        fr:"Rechercher un utilisateur ",
        ara:"البحث عن مستخدم'",
        beng:"ব্যবহারকারী খুঁজুন  ", 
        rus:"Найти пользователя",
        port:"Procurar usuário",
        urd:" صارف تلاش کریں",
        de: ' Benutzer suchen '
    },
    mensajeUsuario :{
        es: 'El usuario aparecera aqui',
        en: 'The user will appear here',
        ch: "用户将出现在这里 ",
        hindi:"उपयोगकर्ता यहाँ दिखाई देगा ",
        fr:"L'utilisateur apparaîtra ici",
        ara:"سيظهر المستخدم هنا'",
        beng:"ব্যবহারকারীটি এখানে দেখানো হবে ", 
        rus:"Пользователь появится здесь ",
        port:"O usuário aparecerá aqui ",
        urd:" صارف یہاں ظاہر ہوگا",
        de: ' Der Benutzer wird hier angezeigt  '
    },
    usuarioEncontrado: {
      es:"Usuario Encontrado",
      en: "User Found",
      ch: "找到用户",
      hindi:"उपयोगकर्ता पाया गया",
      fr:"Utilisateur trouvé",
      ara:"المستخدم موجود",
      beng:"ব্যবহারকারী পাওয়া গেছে  ", 
      rus:"Пользователь найден",
      port:"Usuário encontrado",
      urd:" صارف مل گیا",
      de: ' Benutzer gefunden '
    },
    titulo2 : {
        es: 'Administrador ROL Adminitradores',
        en: 'Administrator role Administrators',
        ch: "管理员 角色 管理员",
        hindi:"प्रशासक भूमिका व्यवस्थापक",
        fr:"Administrateur RÔLE Administrateurs ",
        ara:"مشرف دور المشرفين",
        beng:"প্রশাসক ভূমিকা প্রশাসকবর্গ ", 
        rus:"Администратор РОЛЬ Администраторы",
        port:"Administrador PAPEL Administradores",
        urd:" ایڈمنسٹریٹر کردار منظر رکھنے والے",
        de: ' Administrator ROLLE Administratoren '
    },
    quitarAdmin : {
        es: 'Quitar admin',
        en: 'Remove admin',
        ch: "移除管理员",
        hindi:"व्यवस्थापक हटाएं",
        fr:"Retirer l'admin",
        ara:"إزالة الإداري '",
        beng:"অ্যাডমিন সরান ", 
        rus:"Убрать админа ",
        port:"Remover admin",
        urd:" ایڈمن ہٹائیں",
        de: ' Admin entfernen '
    },
    usuarioNoEncotrado: {
        es: "Usuario no encontrado",
        en: 'User not found',
        ch: "找不到用户",
        hindi:"उपयोगकर्ता नहीं मिला ",
        fr:"Utilisateur non trouvé",
        ara:"المستخدم غير موجود",
        beng:"ব্যবহারকারী পাওয়া যায়নি ", 
        rus:"Пользователь не найден",
        port:"Usuário não encontrado",
        urd:" صارف نہیں مل سکا",
        de: ' Benutzer nicht gefunden'
    },
    usuario: {
        es: "Usuario",
        en: "User",
        ch: "用户",
        hindi:"उपयोगकर्ता",
        fr:"Utilisateur",
        ara:"مستخدم",
        beng:"ব্যবহারকারী ", 
        rus:"Пользователь",
        port:"Usuário",
        urd:" صارف",
        de: ' Benutzer '
    },
    asignarAdmin : {
        es: "Asignarle admin",
        en: "Assign it admin",
        ch: "分配管理员权限 ",
        hindi:"उपयोगकर्ता को व्यवस्थापक दें ",
        fr:"ui attribuer les droits d'admin",
        ara:"تعيينه كمشرف",
        beng:"তাকে অ্যাডমিন দাও ", 
        rus:"Назначить ему админа ",
        port:"Atribuir permissão de admin",
        urd:" اس کو ایڈمن کا تعین دیں",
        de: ' Ihm Admin-Rechte zuweisen  '
    },


}