export const PantallaEstadoSitioLenguaje = {
    miSitios:{
      es: "Mis Sitios",
      en: "My Sites",
      ch: "我的站点", 
      hindi:"मेरी साइटें",
      fr:"Mes Sites",
      ara:"مواقعي '",
      beng:"আমার স্থানগুলি", 
      rus:"Мои Сайты",
      port:"Meus Locais",
      urd:" میری جگہیں",
      de:"Meine Websites",
      
    },
    cantidadSitios:{
        es:"Cantidad de Sitios Subidos",
        en:"Amount of Sites Uploaded",
        ch: "上传的站点数量", 
        hindi:"अपलोड की गई साइटों की संख्या",
        fr:"Nombre de Sites Téléchargés",
        ara:" عدد المواقع التي تم رفعها'",
        beng:"আপলোড করা স্থানের সংখ্যা  ", 
        rus:"Количество загруженных сайтов",
        port:" Número de Locais Enviados",
        urd:"اپ لوڈ کیے گئے جگہوں کی تعداد",
        de:"Anzahl hochgeladener Websites",
    },
    mensajeSinSitio:{
        es:"Al parecer aun no has subido sitios!!!",
        en:"It seems you haven't uploaded sites yet!!!",
        ch: "似乎您还没有上传站点！", 
        hindi:"शायद आपने अभी तक कोई साइट अपलोड नहीं की है !!! ",
        fr:"Apparemment, vous n'avez pas encore téléchargé de sites !!!",
        ara:"يبدو أنك لم تقم برفع أي مواقع بعد!!!",
        beng:"সম্ভবত আপনি এখনও কোন স্থান আপলোড করেননি", 
        rus:"Похоже, вы до сих пор не загрузили сайты!!!",
        port:"Parece que você ainda não enviou nenhum local!!!",
        urd:" معمولاً آپ نے ابھی تک کوئی جگہیں اپ لوڈ نہیں کی ہیں!!!",
        de:"Anscheinend hast du noch keine Websites hochgeladen!!!",
    },

    tituloTexto : {
        es: 'Estado de mis sitios',
        en: 'Status of my sites',
        ch: "我的站点状态", 
        hindi:"मेरी साइटों की स्थिति",
        fr:"État de Mes Sites",
        ara:"حالة مواقعي",
        beng:"আমার স্থানগুলির অবস্থা", 
        rus:"Состояние моих сайтов",
        port:"Estado dos meus locais",
        urd:" میری جگہوں کی حالت",
        de:"Status meiner Websites",
    },
    nombre:{
        es: 'Nombre del Sitio',
        en: 'Name of Site',
        ch: "站点名称 ", 
        hindi:"साइट का नाम ",
        fr:"Nom du Site",
        ara:"اسم الموقع",
        beng:"স্থানের নাম ", 
        rus:"Имя сайта",
        port:"Nome do Local",
        urd:" جگہ کا نام",
        de:"Website-Name",
    },
    estado:{
        es: 'Estado',
        en: 'Status',
        ch: "状态 ", 
        hindi:" स्थिति",
        fr:"État",
        ara:"الحالة'",
        beng:"অবস্থা", 
        rus:"Состояние",
        port:"Estado",
        urd:"حالت",
        de:"Status",
    },
    verSitio:{
        es: 'Ver sitio',
        en: 'See Site',
        ch: "查看站点", 
        hindi:"साइट देखें ",
        fr:"Voir le Site",
        ara:"عرض الموقع",
        beng:"স্থান দেখুন", 
        rus:"Просмотреть сайт",
        port:"Visualizar local",
        urd:" جگہ دیکھیں",
        de:"Website anzeigen",
    },
    eliminar:{
        es: 'Eliminar Sitio',
        en: 'Delete Site',
        ch: "删除站点", 
        hindi:"साइट हटाएँ",
        fr:"Supprimer le Site",
        ara:"حذف الموقع",
        beng:"স্থান মুছুন", 
        rus:" Удалить сайт",
        port:"Excluir loca",
        urd:" جگہ کو حذف کریں",
        de:"Website löschen",
    },
    aprobado: {
        es: "Aprobado",
        en: "Approved",
        ch: "批准",
        hindi: "मंजूर",
        fr: "Approuvé",
        ara: "موافق",
        beng: "অনুমোদিত",
        rus: "Утверждено",
        port: "Aprovado",
        urd: "منظور",
        de: "Genehmigt"
    },
    denegado: {
        es: "Denegado",
        en: "Denied",
        ch: "拒绝",
        hindi: "अस्वीकृत",
        fr: "Refusé",
        ara: "مرفوض",
        beng: "অস্বীকার",
        rus: "Отклонено",
        port: "Negado",
        urd: "منسوخ",
        de: "Abgelehnt"
    },
    revision: {
        es: "Revisión",
        en: "Review",
        ch: "审查",
        hindi: "समीक्षा",
        fr: "Révision",
        ara: "مراجعة",
        beng: "সমীক্ষা",
        rus: "Рецензия",
        port: "Revisão",
        urd: "جائزہ",
        de: "Überprüfung"
    }

}
   