

export const StacksNavigationIdioma = {
        estadoDeSitio: {
                es: "Estado de Sitio",
                en: "Site Status",
                ch: "站点状态",
                hindi: "साइट स्थिति",
                fr: "État du site",
                ara: "حالة الموقع",
                beng: "সাইট অবস্থা",
                rus: "Статус сайта",
                port: "Estado do Site",
                urd: "سائٹ کی حالت",
                de: "Standortstatus",
        },

        inicio: {
                es: "Inicio",
                en: "Home",
                ch: "主页",
                hindi: "घर",
                fr: "Accueil",
                ara: "الصفحة الرئيسية",
                beng: "হোম",
                rus: "Домой",
                port: "Início",
                urd: "ہوم",
                de: "Startseite",
        },
        favoritos: {
                es: "Favoritos",
                en: "Favorites",
                ch: "收藏夹",
                hindi: "पसंदीदा",
                fr: "Favoris",
                ara: "المفضلة",
                beng: "প্রিয়জন",
                rus: "Избранные",
                port: "Favoritos",
                urd: "پسندیدہ",
                de: "Favoriten",
        },
        iniciarSesion: {
                es: "Iniciar Sesión",
                en: "Log In",
                ch: "登录",
                hindi: "लॉग इन करें",
                fr: "Se connecter",
                ara: "تسجيل الدخول",
                beng: "লগইন করুন",
                rus: "Войти",
                port: "Iniciar Sessão",
                urd: "لاگ ان کریں",
                de: "Anmelden",
        },
        nuevoSitio: {
                es: "Agregar Sitio",
                en: "Add Site",
                ch: "添加位置",
                hindi: "स्थान जोड़ें",
                fr: "Ajouter un emplacement",
                ara: "إضافة موقع",
                beng: "স্থান যোগ করুন",
                rus: "Добавить местоположение",
                port: "Adicionar Local",
                urd: "مقام شامل کریں",
                de: "Standort hinzufügen",
        },
        administradorDeAnuncios: {
                es: "Administrador de Anuncios",
                en: "Ad Manager",
                ch: "广告管理员",
                hindi: "विज्ञापन प्रबंधक",
                fr: "Gestionnaire de publicités",
                ara: "مدير الإعلانات",
                beng: "বিজ্ঞাপন পরিচালক",
                rus: "Менеджер рекламы",
                port: "Gerente de Anúncios",
                urd: "اشتہار مینجر",
                de: "Anzeigenverwalter",
        },

        administradorDeSitios: {
                es: "Administrador de Sitios",
                en: "Site Manager",
                ch: "站点管理员",
                hindi: "साइट प्रबंधक",
                fr: "Gestionnaire de site",
                ara: "مدير الموقع",
                beng: "সাইট পরিচালক",
                rus: "Менеджер сайта",
                port: "Gerente de Site",
                urd: "سائٹ منیجر",
                de: "Standortmanager",
        },
        vistaDeSitio: {
                es: "Vista de Sitio",
                en: "Site View",
                ch: "站点视图",
                hindi: "साइट दृश्य",
                fr: "Vue du site",
                ara: "عرض الموقع",
                beng: "সাইট দৃশ্য",
                rus: "Просмотр сайта",
                port: "Visualização do Site",
                urd: "سائٹ دیکھیں",
                de: "Seitenansicht",
        },


        administracionDeUsuarios: {
                es: "Administración de Usuarios",
                en: "User Administration",
                ch: "用户管理",
                hindi: "उपयोगकर्ता प्रशासन",
                fr: "Administration des utilisateurs",
                ara: "إدارة المستخدمين",
                beng: "ব্যবহারকারী প্রশাসন",
                rus: "Администрирование пользователей",
                port: "Administração de Usuários",
                urd: "صارف کا انتظام",
                de: "Benutzerverwaltung",
        },

}
